apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: crework-trello
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # This will be created via kubectl create secret docker-registry

---
# To create this secret, run:
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=<DOCKERHUB_USERNAME> \
#   --docker-password=<DOCKERHUB_TOKEN> \
#   --docker-email=<EMAIL> \
#   --namespace=crework-trello
